master:
  container_name: salt-master
  image: dawidmalina/docker-salt-master:14.04
  privileged: true
  environment:
    LOG_LEVEL: info
  hostname: master
  expose:
    - "4505"
    - "4506"
  volumes:
    - ./salt:/srv/salt/:rw
    - ./ext_pillar.conf:/etc/salt/master.d/ext_pillar.conf:rw

minion1:
  container_name: salt-slave-ubuntu-14-04
  image: dawidmalina/docker-salt-slave-ubuntu:14.04
  links:
   - master
  environment:
    LOG_LEVEL: info
  hostname: minion1

minion2:
  container_name: salt-slave-centos-7-1
  image: dawidmalina/docker-salt-slave-centos:7.1
  links:
   - master
  environment:
    LOG_LEVEL: info
  hostname: minion2

minion3:
  container_name: salt-slave-ubuntu-15-10
  image: dawidmalina/docker-salt-slave-ubuntu:15.10
  links:
   - master
  environment:
    LOG_LEVEL: info
  hostname: minion3