master:
  container_name: salt-master
  image: dawidmalina/docker-salt-master:18.04
  privileged: true
  environment:
    LOG_LEVEL: info
  hostname: master
  entrypoint: /sbin/init
  expose:
    - "4505"
    - "4506"
  volumes:
    - ./srv/salt:/srv/salt:rw
    - ./etc/salt/master.d:/etc/salt/master.d:rw
    - ./etc/salt/minion.d:/etc/salt/minion.d:rw

ubuntu-16-04:
  container_name: salt-slave-ubuntu-16-04
  image: dawidmalina/docker-salt-slave-ubuntu:16.04
  privileged: true
  links:
   - master
  environment:
    LOG_LEVEL: info
  hostname: ubuntu-16-04
  entrypoint: /sbin/init
  volumes:
    - ./etc/salt/minion.d:/etc/salt/minion.d:rw

ubuntu-18-04:
  container_name: salt-slave-ubuntu-18-04
  image: dawidmalina/docker-salt-slave-ubuntu:18.04
  privileged: true
  links:
   - master
  environment:
    LOG_LEVEL: info
  hostname: ubuntu-18-04
  entrypoint: /sbin/init
  volumes:
    - ./etc/salt/minion.d:/etc/salt/minion.d:rw

centos-7:
  container_name: salt-slave-centos-7
  image: dawidmalina/docker-salt-slave-centos:7
  privileged: true
  links:
   - master
  environment:
    LOG_LEVEL: info
  hostname: centos-7
  entrypoint: /usr/sbin/init
  volumes:
    - ./etc/salt/minion.d:/etc/salt/minion.d:rw
